//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMLAssertion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ec2-50-16-98-152.compute-1.amazonaws.com:8080/HarrisIntegrationServices/St" +
            "oreDocumentIntegrationService")]
        public string SAMLAssertion_HarrisStore_EntityXDR_Service {
            get {
                return ((string)(this["SAMLAssertion_HarrisStore_EntityXDR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ec2-50-16-98-152.compute-1.amazonaws.com:8080/HarrisIntegrationServices/Do" +
            "cQueryIntegrationService")]
        public string SAMLAssertion_DocQuery_EntityDocQuery {
            get {
                return ((string)(this["SAMLAssertion_DocQuery_EntityDocQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ec2-50-16-98-152.compute-1.amazonaws.com:8080/HarrisIntegrationServices/Do" +
            "cumentRetrieveIntegrationService")]
        public string SAMLAssertion_RetrieveDocument_EntityDocRetrieve {
            get {
                return ((string)(this["SAMLAssertion_RetrieveDocument_EntityDocRetrieve"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.0.30.61:8008/SAMLService/SamlService1.asmx")]
        public string SAMLAssertion_SAMLService_SamlService1 {
            get {
                return ((string)(this["SAMLAssertion_SAMLService_SamlService1"]));
            }
        }
    }
}
