//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18052.
// 
#pragma warning disable 1591
//THIS IS SERVICE REFERENCE 
namespace AdapterPEP
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using Mobius.CoreLibrary;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AdapterPEPBindingSoap", Namespace="urn:gov:hhs:fha:nhinc:adapterpep")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExpressionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActionType))]
    public partial class AdapterPEP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckPolicyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AdapterPEP() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;                        
            this.Url = MobiusAppSettingReader.NHINPolicyEngineURL;
            this.Timeout = MobiusAppSettingReader.ConnectGatewayTimeOut;

        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckPolicyCompletedEventHandler CheckPolicyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:CheckPolicy", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CheckPolicyResponse", Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter")]
        public CheckPolicyResponseType CheckPolicy([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter")] CheckPolicyRequestType CheckPolicyRequest) {
            object[] results = this.Invoke("CheckPolicy", new object[] {
                        CheckPolicyRequest});
            return ((CheckPolicyResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void CheckPolicyAsync(CheckPolicyRequestType CheckPolicyRequest) {
            this.CheckPolicyAsync(CheckPolicyRequest, null);
        }
        
        /// <remarks/>
        public void CheckPolicyAsync(CheckPolicyRequestType CheckPolicyRequest, object userState) {
            if ((this.CheckPolicyOperationCompleted == null)) {
                this.CheckPolicyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckPolicyOperationCompleted);
            }
            this.InvokeAsync("CheckPolicy", new object[] {
                        CheckPolicyRequest}, this.CheckPolicyOperationCompleted, userState);
        }
        
        private void OnCheckPolicyOperationCompleted(object arg) {
            if ((this.CheckPolicyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckPolicyCompleted(this, new CheckPolicyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter")]
    public partial class CheckPolicyRequestType {
        
        private AssertionType assertionField;
        
        private RequestType requestField;
        
        /// <remarks/>
        public AssertionType assertion {
            get {
                return this.assertionField;
            }
            set {
                this.assertionField = value;
            }
        }
        
        /// <remarks/>
        public RequestType request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class AssertionType {
        
        private AddressType addressField;
        
        private string dateOfBirthField;
        
        private string explanationNonClaimantSignatureField;
        
        private bool haveSecondWitnessSignatureField;
        
        private bool haveSignatureField;
        
        private bool haveWitnessSignatureField;
        
        private HomeCommunityType homeCommunityField;
        
        private string nationalProviderIdField;
        
        private PersonNameType personNameField;
        
        private PhoneType phoneNumberField;
        
        private AddressType secondWitnessAddressField;
        
        private PersonNameType secondWitnessNameField;
        
        private PhoneType secondWitnessPhoneField;
        
        private string sSNField;
        
        private string[] uniquePatientIdField;
        
        private AddressType witnessAddressField;
        
        private PersonNameType witnessNameField;
        
        private PhoneType witnessPhoneField;
        
        private UserType userInfoField;
        
        private bool authorizedField;
        
        private CeType purposeOfDisclosureCodedField;
        
        private SamlAuthnStatementType samlAuthnStatementField;
        
        private SamlAuthzDecisionStatementType samlAuthzDecisionStatementField;
        
        private SamlSignatureType samlSignatureField;
        
        private SamlIssuerType samlIssuerField;
        
        private string messageIdField;
        
        private string[] relatesToListField;
        
        /// <remarks/>
        public AddressType address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string dateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string explanationNonClaimantSignature {
            get {
                return this.explanationNonClaimantSignatureField;
            }
            set {
                this.explanationNonClaimantSignatureField = value;
            }
        }
        
        /// <remarks/>
        public bool haveSecondWitnessSignature {
            get {
                return this.haveSecondWitnessSignatureField;
            }
            set {
                this.haveSecondWitnessSignatureField = value;
            }
        }
        
        /// <remarks/>
        public bool haveSignature {
            get {
                return this.haveSignatureField;
            }
            set {
                this.haveSignatureField = value;
            }
        }
        
        /// <remarks/>
        public bool haveWitnessSignature {
            get {
                return this.haveWitnessSignatureField;
            }
            set {
                this.haveWitnessSignatureField = value;
            }
        }
        
        /// <remarks/>
        public HomeCommunityType homeCommunity {
            get {
                return this.homeCommunityField;
            }
            set {
                this.homeCommunityField = value;
            }
        }
        
        /// <remarks/>
        public string nationalProviderId {
            get {
                return this.nationalProviderIdField;
            }
            set {
                this.nationalProviderIdField = value;
            }
        }
        
        /// <remarks/>
        public PersonNameType personName {
            get {
                return this.personNameField;
            }
            set {
                this.personNameField = value;
            }
        }
        
        /// <remarks/>
        public PhoneType phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public AddressType secondWitnessAddress {
            get {
                return this.secondWitnessAddressField;
            }
            set {
                this.secondWitnessAddressField = value;
            }
        }
        
        /// <remarks/>
        public PersonNameType secondWitnessName {
            get {
                return this.secondWitnessNameField;
            }
            set {
                this.secondWitnessNameField = value;
            }
        }
        
        /// <remarks/>
        public PhoneType secondWitnessPhone {
            get {
                return this.secondWitnessPhoneField;
            }
            set {
                this.secondWitnessPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string SSN {
            get {
                return this.sSNField;
            }
            set {
                this.sSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("uniquePatientId")]
        public string[] uniquePatientId {
            get {
                return this.uniquePatientIdField;
            }
            set {
                this.uniquePatientIdField = value;
            }
        }
        
        /// <remarks/>
        public AddressType witnessAddress {
            get {
                return this.witnessAddressField;
            }
            set {
                this.witnessAddressField = value;
            }
        }
        
        /// <remarks/>
        public PersonNameType witnessName {
            get {
                return this.witnessNameField;
            }
            set {
                this.witnessNameField = value;
            }
        }
        
        /// <remarks/>
        public PhoneType witnessPhone {
            get {
                return this.witnessPhoneField;
            }
            set {
                this.witnessPhoneField = value;
            }
        }
        
        /// <remarks/>
        public UserType userInfo {
            get {
                return this.userInfoField;
            }
            set {
                this.userInfoField = value;
            }
        }
        
        /// <remarks/>
        public bool authorized {
            get {
                return this.authorizedField;
            }
            set {
                this.authorizedField = value;
            }
        }
        
        /// <remarks/>
        public CeType purposeOfDisclosureCoded {
            get {
                return this.purposeOfDisclosureCodedField;
            }
            set {
                this.purposeOfDisclosureCodedField = value;
            }
        }
        
        /// <remarks/>
        public SamlAuthnStatementType samlAuthnStatement {
            get {
                return this.samlAuthnStatementField;
            }
            set {
                this.samlAuthnStatementField = value;
            }
        }
        
        /// <remarks/>
        public SamlAuthzDecisionStatementType samlAuthzDecisionStatement {
            get {
                return this.samlAuthzDecisionStatementField;
            }
            set {
                this.samlAuthzDecisionStatementField = value;
            }
        }
        
        /// <remarks/>
        public SamlSignatureType samlSignature {
            get {
                return this.samlSignatureField;
            }
            set {
                this.samlSignatureField = value;
            }
        }
        
        /// <remarks/>
        public SamlIssuerType samlIssuer {
            get {
                return this.samlIssuerField;
            }
            set {
                this.samlIssuerField = value;
            }
        }
        
        /// <remarks/>
        public string messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("relatesToList")]
        public string[] relatesToList {
            get {
                return this.relatesToListField;
            }
            set {
                this.relatesToListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class AddressType {
        
        private CeType addressTypeField;
        
        private string cityField;
        
        private string countryField;
        
        private string stateField;
        
        private string streetAddressField;
        
        private string zipCodeField;
        
        /// <remarks/>
        public CeType addressType {
            get {
                return this.addressTypeField;
            }
            set {
                this.addressTypeField = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string streetAddress {
            get {
                return this.streetAddressField;
            }
            set {
                this.streetAddressField = value;
            }
        }
        
        /// <remarks/>
        public string zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class CeType {
        
        private string codeField;
        
        private string codeSystemField;
        
        private string codeSystemNameField;
        
        private string codeSystemVersionField;
        
        private string displayNameField;
        
        private string originalTextField;
        
        private CeType[] translationField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string codeSystem {
            get {
                return this.codeSystemField;
            }
            set {
                this.codeSystemField = value;
            }
        }
        
        /// <remarks/>
        public string codeSystemName {
            get {
                return this.codeSystemNameField;
            }
            set {
                this.codeSystemNameField = value;
            }
        }
        
        /// <remarks/>
        public string codeSystemVersion {
            get {
                return this.codeSystemVersionField;
            }
            set {
                this.codeSystemVersionField = value;
            }
        }
        
        /// <remarks/>
        public string displayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string originalText {
            get {
                return this.originalTextField;
            }
            set {
                this.originalTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("translation")]
        public CeType[] translation {
            get {
                return this.translationField;
            }
            set {
                this.translationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ApplyType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FunctionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttributeValueType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttributeAssignmentType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttributeDesignatorType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectAttributeDesignatorType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttributeSelectorType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VariableReferenceType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:xacml:2.0:policy:schema:os")]
    public abstract partial class ExpressionType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:xacml:2.0:policy:schema:os")]
    public partial class ApplyType : ExpressionType {
        
        private ExpressionType[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private string functionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActionAttributeDesignator", typeof(AttributeDesignatorType))]
        [System.Xml.Serialization.XmlElementAttribute("Apply", typeof(ApplyType))]
        [System.Xml.Serialization.XmlElementAttribute("AttributeSelector", typeof(AttributeSelectorType))]
        [System.Xml.Serialization.XmlElementAttribute("AttributeValue", typeof(AttributeValueType))]
        [System.Xml.Serialization.XmlElementAttribute("EnvironmentAttributeDesignator", typeof(AttributeDesignatorType))]
        [System.Xml.Serialization.XmlElementAttribute("Function", typeof(FunctionType))]
        [System.Xml.Serialization.XmlElementAttribute("ResourceAttributeDesignator", typeof(AttributeDesignatorType))]
        [System.Xml.Serialization.XmlElementAttribute("SubjectAttributeDesignator", typeof(SubjectAttributeDesignatorType))]
        [System.Xml.Serialization.XmlElementAttribute("VariableReference", typeof(VariableReferenceType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public ExpressionType[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string FunctionId {
            get {
                return this.functionIdField;
            }
            set {
                this.functionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectAttributeDesignatorType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:xacml:2.0:policy:schema:os")]
    public partial class AttributeDesignatorType : ExpressionType {
        
        private string attributeIdField;
        
        private string dataTypeField;
        
        private string issuerField;
        
        private bool mustBePresentField;
        
        public AttributeDesignatorType() {
            this.mustBePresentField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string AttributeId {
            get {
                return this.attributeIdField;
            }
            set {
                this.attributeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Issuer {
            get {
                return this.issuerField;
            }
            set {
                this.issuerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool MustBePresent {
            get {
                return this.mustBePresentField;
            }
            set {
                this.mustBePresentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:xacml:2.0:policy:schema:os")]
    public partial class SubjectAttributeDesignatorType : AttributeDesignatorType {
        
        private string subjectCategoryField;
        
        public SubjectAttributeDesignatorType() {
            this.subjectCategoryField = "urn:oasis:names:tc:xacml:1.0:subject-category:access-subject";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        [System.ComponentModel.DefaultValueAttribute("urn:oasis:names:tc:xacml:1.0:subject-category:access-subject")]
        public string SubjectCategory {
            get {
                return this.subjectCategoryField;
            }
            set {
                this.subjectCategoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:xacml:2.0:policy:schema:os")]
    public partial class AttributeSelectorType : ExpressionType {
        
        private string requestContextPathField;
        
        private string dataTypeField;
        
        private bool mustBePresentField;
        
        public AttributeSelectorType() {
            this.mustBePresentField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RequestContextPath {
            get {
                return this.requestContextPathField;
            }
            set {
                this.requestContextPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool MustBePresent {
            get {
                return this.mustBePresentField;
            }
            set {
                this.mustBePresentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttributeAssignmentType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:xacml:2.0:policy:schema:os")]
    public partial class AttributeValueType : ExpressionType {
        
        private System.Xml.XmlNode[] anyField;
        
        private string dataTypeField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:xacml:2.0:policy:schema:os")]
    public partial class AttributeAssignmentType : AttributeValueType {
        
        private string attributeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string AttributeId {
            get {
                return this.attributeIdField;
            }
            set {
                this.attributeIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:xacml:2.0:policy:schema:os")]
    public partial class FunctionType : ExpressionType {
        
        private string functionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string FunctionId {
            get {
                return this.functionIdField;
            }
            set {
                this.functionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:xacml:2.0:policy:schema:os")]
    public partial class VariableReferenceType : ExpressionType {
        
        private string variableIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VariableId {
            get {
                return this.variableIdField;
            }
            set {
                this.variableIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:xacml:2.0:policy:schema:os", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        ActionAttributeDesignator,
        
        /// <remarks/>
        Apply,
        
        /// <remarks/>
        AttributeSelector,
        
        /// <remarks/>
        AttributeValue,
        
        /// <remarks/>
        EnvironmentAttributeDesignator,
        
        /// <remarks/>
        Function,
        
        /// <remarks/>
        ResourceAttributeDesignator,
        
        /// <remarks/>
        SubjectAttributeDesignator,
        
        /// <remarks/>
        VariableReference,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:xacml:2.0:policy:schema:os")]
    public partial class ObligationType {
        
        private AttributeAssignmentType[] attributeAssignmentField;
        
        private string obligationIdField;
        
        private EffectType fulfillOnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttributeAssignment")]
        public AttributeAssignmentType[] AttributeAssignment {
            get {
                return this.attributeAssignmentField;
            }
            set {
                this.attributeAssignmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string ObligationId {
            get {
                return this.obligationIdField;
            }
            set {
                this.obligationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public EffectType FulfillOn {
            get {
                return this.fulfillOnField;
            }
            set {
                this.fulfillOnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:xacml:2.0:policy:schema:os")]
    public enum EffectType {
        
        /// <remarks/>
        Permit,
        
        /// <remarks/>
        Deny,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:xacml:2.0:context:schema:os")]
    public partial class StatusDetailType {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:xacml:2.0:context:schema:os")]
    public partial class StatusCodeType {
        
        private StatusCodeType statusCodeField;
        
        private string valueField;
        
        /// <remarks/>
        public StatusCodeType StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:xacml:2.0:context:schema:os")]
    public partial class StatusType {
        
        private StatusCodeType statusCodeField;
        
        private string statusMessageField;
        
        private StatusDetailType statusDetailField;
        
        /// <remarks/>
        public StatusCodeType StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
            }
        }
        
        /// <remarks/>
        public StatusDetailType StatusDetail {
            get {
                return this.statusDetailField;
            }
            set {
                this.statusDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:xacml:2.0:context:schema:os")]
    public partial class ResultType {
        
        private DecisionType decisionField;
        
        private StatusType statusField;
        
        private ObligationType[] obligationsField;
        
        private string resourceIdField;
        
        /// <remarks/>
        public DecisionType Decision {
            get {
                return this.decisionField;
            }
            set {
                this.decisionField = value;
            }
        }
        
        /// <remarks/>
        public StatusType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:oasis:names:tc:xacml:2.0:policy:schema:os")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Obligation", IsNullable=false)]
        public ObligationType[] Obligations {
            get {
                return this.obligationsField;
            }
            set {
                this.obligationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ResourceId {
            get {
                return this.resourceIdField;
            }
            set {
                this.resourceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:xacml:2.0:context:schema:os")]
    public enum DecisionType {
        
        /// <remarks/>
        Permit,
        
        /// <remarks/>
        Deny,
        
        /// <remarks/>
        Indeterminate,
        
        /// <remarks/>
        NotApplicable,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter")]
    public partial class CheckPolicyResponseType {
        
        private ResultType[] responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Result", Namespace="urn:oasis:names:tc:xacml:2.0:context:schema:os", IsNullable=false)]
        public ResultType[] response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ActionType", Namespace="urn:oasis:names:tc:xacml:2.0:context:schema:os")]
    public partial class ActionType1 {
        
        private AttributeType[] attributeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attribute")]
        public AttributeType[] Attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:xacml:2.0:context:schema:os")]
    public partial class AttributeType {
        
        private System.Xml.XmlElement[] attributeValueField;
        
        private string attributeIdField;
        
        private string dataTypeField;
        
        private string issuerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Name="AttributeValue", Namespace="urn:oasis:names:tc:xacml:2.0:context:schema:os")]
        public System.Xml.XmlElement[] AttributeValue {
            get {
                return this.attributeValueField;
            }
            set {
                this.attributeValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string AttributeId {
            get {
                return this.attributeIdField;
            }
            set {
                this.attributeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Issuer {
            get {
                return this.issuerField;
            }
            set {
                this.issuerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NotifyActionType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
    public abstract partial class ActionType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
    public partial class NotifyActionType : ActionType {
        
        private string notificationOptionField;
        
        private string endPointField;
        
        public NotifyActionType() {
            this.notificationOptionField = "urn:oasis:names:tc:ebxml-regrep:NotificationOptionType:ObjectRefs";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        [System.ComponentModel.DefaultValueAttribute("urn:oasis:names:tc:ebxml-regrep:NotificationOptionType:ObjectRefs")]
        public string notificationOption {
            get {
                return this.notificationOptionField;
            }
            set {
                this.notificationOptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string endPoint {
            get {
                return this.endPointField;
            }
            set {
                this.endPointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:xacml:2.0:context:schema:os")]
    public partial class ResourceType {
        
        private System.Xml.XmlElement resourceContentField;
        
        private AttributeType[] attributeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Name="ResourceContent", Namespace="urn:oasis:names:tc:xacml:2.0:context:schema:os")]
        public System.Xml.XmlElement ResourceContent {
            get {
                return this.resourceContentField;
            }
            set {
                this.resourceContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attribute")]
        public AttributeType[] Attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:xacml:2.0:context:schema:os")]
    public partial class SubjectType {
        
        private AttributeType[] attributeField;
        
        private string subjectCategoryField;
        
        public SubjectType() {
            this.subjectCategoryField = "urn:oasis:names:tc:xacml:1.0:subject-category:access-subject";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attribute")]
        public AttributeType[] Attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        [System.ComponentModel.DefaultValueAttribute("urn:oasis:names:tc:xacml:1.0:subject-category:access-subject")]
        public string SubjectCategory {
            get {
                return this.subjectCategoryField;
            }
            set {
                this.subjectCategoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:xacml:2.0:context:schema:os")]
    public partial class RequestType {
        
        private SubjectType[] subjectField;
        
        private ResourceType[] resourceField;
        
        private object itemField;
        
        private AttributeType[] environmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Subject")]
        public SubjectType[] Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Resource")]
        public ResourceType[] Resource {
            get {
                return this.resourceField;
            }
            set {
                this.resourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NotifyAction", typeof(NotifyActionType), Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
        [System.Xml.Serialization.XmlElementAttribute("Action", typeof(ActionType1))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Attribute", IsNullable=false)]
        public AttributeType[] Environment {
            get {
                return this.environmentField;
            }
            set {
                this.environmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class SamlIssuerType {
        
        private string issuerField;
        
        private string issuerFormatField;
        
        /// <remarks/>
        public string issuer {
            get {
                return this.issuerField;
            }
            set {
                this.issuerField = value;
            }
        }
        
        /// <remarks/>
        public string issuerFormat {
            get {
                return this.issuerFormatField;
            }
            set {
                this.issuerFormatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class SamlSignatureKeyInfoType {
        
        private byte[] rsaKeyValueModulusField;
        
        private byte[] rsaKeyValueExponentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] rsaKeyValueModulus {
            get {
                return this.rsaKeyValueModulusField;
            }
            set {
                this.rsaKeyValueModulusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] rsaKeyValueExponent {
            get {
                return this.rsaKeyValueExponentField;
            }
            set {
                this.rsaKeyValueExponentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class SamlSignatureType {
        
        private SamlSignatureKeyInfoType keyInfoField;
        
        private byte[] signatureValueField;
        
        /// <remarks/>
        public SamlSignatureKeyInfoType keyInfo {
            get {
                return this.keyInfoField;
            }
            set {
                this.keyInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] signatureValue {
            get {
                return this.signatureValueField;
            }
            set {
                this.signatureValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class SamlAuthzDecisionStatementEvidenceConditionsType {
        
        private string notBeforeField;
        
        private string notOnOrAfterField;
        
        /// <remarks/>
        public string notBefore {
            get {
                return this.notBeforeField;
            }
            set {
                this.notBeforeField = value;
            }
        }
        
        /// <remarks/>
        public string notOnOrAfter {
            get {
                return this.notOnOrAfterField;
            }
            set {
                this.notOnOrAfterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class SamlAuthzDecisionStatementEvidenceAssertionType {
        
        private string idField;
        
        private string issueInstantField;
        
        private string versionField;
        
        private string issuerField;
        
        private string issuerFormatField;
        
        private string subjectField;
        
        private SamlAuthzDecisionStatementEvidenceConditionsType conditionsField;
        
        private string[] accessConsentPolicyField;
        
        private string[] instanceAccessConsentPolicyField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string issueInstant {
            get {
                return this.issueInstantField;
            }
            set {
                this.issueInstantField = value;
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string issuer {
            get {
                return this.issuerField;
            }
            set {
                this.issuerField = value;
            }
        }
        
        /// <remarks/>
        public string issuerFormat {
            get {
                return this.issuerFormatField;
            }
            set {
                this.issuerFormatField = value;
            }
        }
        
        /// <remarks/>
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public SamlAuthzDecisionStatementEvidenceConditionsType conditions {
            get {
                return this.conditionsField;
            }
            set {
                this.conditionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("accessConsentPolicy")]
        public string[] accessConsentPolicy {
            get {
                return this.accessConsentPolicyField;
            }
            set {
                this.accessConsentPolicyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("instanceAccessConsentPolicy")]
        public string[] instanceAccessConsentPolicy {
            get {
                return this.instanceAccessConsentPolicyField;
            }
            set {
                this.instanceAccessConsentPolicyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class SamlAuthzDecisionStatementEvidenceType {
        
        private SamlAuthzDecisionStatementEvidenceAssertionType assertionField;
        
        /// <remarks/>
        public SamlAuthzDecisionStatementEvidenceAssertionType assertion {
            get {
                return this.assertionField;
            }
            set {
                this.assertionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class SamlAuthzDecisionStatementType {
        
        private string decisionField;
        
        private string resourceField;
        
        private string actionField;
        
        private SamlAuthzDecisionStatementEvidenceType evidenceField;
        
        /// <remarks/>
        public string decision {
            get {
                return this.decisionField;
            }
            set {
                this.decisionField = value;
            }
        }
        
        /// <remarks/>
        public string resource {
            get {
                return this.resourceField;
            }
            set {
                this.resourceField = value;
            }
        }
        
        /// <remarks/>
        public string action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        public SamlAuthzDecisionStatementEvidenceType evidence {
            get {
                return this.evidenceField;
            }
            set {
                this.evidenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class SamlAuthnStatementType {
        
        private string authInstantField;
        
        private string sessionIndexField;
        
        private string authContextClassRefField;
        
        private string subjectLocalityAddressField;
        
        private string subjectLocalityDNSNameField;
        
        /// <remarks/>
        public string authInstant {
            get {
                return this.authInstantField;
            }
            set {
                this.authInstantField = value;
            }
        }
        
        /// <remarks/>
        public string sessionIndex {
            get {
                return this.sessionIndexField;
            }
            set {
                this.sessionIndexField = value;
            }
        }
        
        /// <remarks/>
        public string authContextClassRef {
            get {
                return this.authContextClassRefField;
            }
            set {
                this.authContextClassRefField = value;
            }
        }
        
        /// <remarks/>
        public string subjectLocalityAddress {
            get {
                return this.subjectLocalityAddressField;
            }
            set {
                this.subjectLocalityAddressField = value;
            }
        }
        
        /// <remarks/>
        public string subjectLocalityDNSName {
            get {
                return this.subjectLocalityDNSNameField;
            }
            set {
                this.subjectLocalityDNSNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class UserType {
        
        private PersonNameType personNameField;
        
        private string userNameField;
        
        private HomeCommunityType orgField;
        
        private CeType roleCodedField;
        
        /// <remarks/>
        public PersonNameType personName {
            get {
                return this.personNameField;
            }
            set {
                this.personNameField = value;
            }
        }
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public HomeCommunityType org {
            get {
                return this.orgField;
            }
            set {
                this.orgField = value;
            }
        }
        
        /// <remarks/>
        public CeType roleCoded {
            get {
                return this.roleCodedField;
            }
            set {
                this.roleCodedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class PersonNameType {
        
        private string familyNameField;
        
        private string givenNameField;
        
        private CeType nameTypeField;
        
        private string secondNameOrInitialsField;
        
        private string fullNameField;
        
        private string prefixField;
        
        private string suffixField;
        
        /// <remarks/>
        public string familyName {
            get {
                return this.familyNameField;
            }
            set {
                this.familyNameField = value;
            }
        }
        
        /// <remarks/>
        public string givenName {
            get {
                return this.givenNameField;
            }
            set {
                this.givenNameField = value;
            }
        }
        
        /// <remarks/>
        public CeType nameType {
            get {
                return this.nameTypeField;
            }
            set {
                this.nameTypeField = value;
            }
        }
        
        /// <remarks/>
        public string secondNameOrInitials {
            get {
                return this.secondNameOrInitialsField;
            }
            set {
                this.secondNameOrInitialsField = value;
            }
        }
        
        /// <remarks/>
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public string prefix {
            get {
                return this.prefixField;
            }
            set {
                this.prefixField = value;
            }
        }
        
        /// <remarks/>
        public string suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class HomeCommunityType {
        
        private string descriptionField;
        
        private string homeCommunityIdField;
        
        private string nameField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string homeCommunityId {
            get {
                return this.homeCommunityIdField;
            }
            set {
                this.homeCommunityIdField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class PhoneType {
        
        private string areaCodeField;
        
        private string countryCodeField;
        
        private string extensionField;
        
        private string localNumberField;
        
        private CeType phoneNumberTypeField;
        
        /// <remarks/>
        public string areaCode {
            get {
                return this.areaCodeField;
            }
            set {
                this.areaCodeField = value;
            }
        }
        
        /// <remarks/>
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        public string localNumber {
            get {
                return this.localNumberField;
            }
            set {
                this.localNumberField = value;
            }
        }
        
        /// <remarks/>
        public CeType phoneNumberType {
            get {
                return this.phoneNumberTypeField;
            }
            set {
                this.phoneNumberTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CheckPolicyCompletedEventHandler(object sender, CheckPolicyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckPolicyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckPolicyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CheckPolicyResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CheckPolicyResponseType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591