//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5448.
// 
#pragma warning disable 1591

namespace RetrieveDocument
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using Mobius.CoreLibrary;
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EntityDocRetrieveBindingSoap", Namespace="urn:gov:hhs:fha:nhinc:entitydocretrieve")]

    public partial class EntityDocRetrieve : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RespondingGateway_CrossGatewayRetrieveOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EntityDocRetrieve() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = MobiusAppSettingReader.NHINRetrieveDocumentURL;
            //this.Url = "http://71.28.159.148:8080/HarrisIntegrationServices/DocumentRetrieveIntegrationService";

            this.Timeout = MobiusAppSettingReader.ConnectGatewayTimeOut;
            
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RespondingGateway_CrossGatewayRetrieveCompletedEventHandler RespondingGateway_CrossGatewayRetrieveCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:RespondingGateway_CrossGatewayRetrieve", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RetrieveDocumentSetResponse", Namespace="urn:ihe:iti:xds-b:2007")]
        public RetrieveDocumentSetResponseType RespondingGateway_CrossGatewayRetrieve([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonentity")] RespondingGateway_CrossGatewayRetrieveRequestType RespondingGateway_CrossGatewayRetrieveRequest) {
            object[] results = this.Invoke("RespondingGateway_CrossGatewayRetrieve", new object[] {
                        RespondingGateway_CrossGatewayRetrieveRequest});
            return ((RetrieveDocumentSetResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void RespondingGateway_CrossGatewayRetrieveAsync(RespondingGateway_CrossGatewayRetrieveRequestType RespondingGateway_CrossGatewayRetrieveRequest) {
            this.RespondingGateway_CrossGatewayRetrieveAsync(RespondingGateway_CrossGatewayRetrieveRequest, null);
        }
        
        /// <remarks/>
        public void RespondingGateway_CrossGatewayRetrieveAsync(RespondingGateway_CrossGatewayRetrieveRequestType RespondingGateway_CrossGatewayRetrieveRequest, object userState) {
            if ((this.RespondingGateway_CrossGatewayRetrieveOperationCompleted == null)) {
                this.RespondingGateway_CrossGatewayRetrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRespondingGateway_CrossGatewayRetrieveOperationCompleted);
            }
            this.InvokeAsync("RespondingGateway_CrossGatewayRetrieve", new object[] {
                        RespondingGateway_CrossGatewayRetrieveRequest}, this.RespondingGateway_CrossGatewayRetrieveOperationCompleted, userState);
        }
        
        private void OnRespondingGateway_CrossGatewayRetrieveOperationCompleted(object arg) {
            if ((this.RespondingGateway_CrossGatewayRetrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RespondingGateway_CrossGatewayRetrieveCompleted(this, new RespondingGateway_CrossGatewayRetrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonentity")]
    public partial class RespondingGateway_CrossGatewayRetrieveRequestType {
        
        private RetrieveDocumentSetRequestTypeDocumentRequest[] retrieveDocumentSetRequestField;
        
        private AssertionType assertionField;
        
        private NhinTargetCommunityType[] nhinTargetCommunitiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:ihe:iti:xds-b:2007")]
        [System.Xml.Serialization.XmlArrayItemAttribute("DocumentRequest", IsNullable=false)]
        public RetrieveDocumentSetRequestTypeDocumentRequest[] RetrieveDocumentSetRequest {
            get {
                return this.retrieveDocumentSetRequestField;
            }
            set {
                this.retrieveDocumentSetRequestField = value;
            }
        }
        
        /// <remarks/>
        public AssertionType assertion {
            get {
                return this.assertionField;
            }
            set {
                this.assertionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("nhinTargetCommunity", Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon", IsNullable=false)]
        public NhinTargetCommunityType[] NhinTargetCommunities {
            get {
                return this.nhinTargetCommunitiesField;
            }
            set {
                this.nhinTargetCommunitiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ihe:iti:xds-b:2007")]
    public partial class RetrieveDocumentSetRequestTypeDocumentRequest {
        
        private string homeCommunityIdField;
        
        private string repositoryUniqueIdField;
        
        private string documentUniqueIdField;
        
        /// <remarks/>
        public string HomeCommunityId {
            get {
                return this.homeCommunityIdField;
            }
            set {
                this.homeCommunityIdField = value;
            }
        }
        
        /// <remarks/>
        public string RepositoryUniqueId {
            get {
                return this.repositoryUniqueIdField;
            }
            set {
                this.repositoryUniqueIdField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentUniqueId {
            get {
                return this.documentUniqueIdField;
            }
            set {
                this.documentUniqueIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
    public partial class ValueListType {
        
        private string[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public string[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
    public partial class SlotType1 {
        
        private ValueListType valueListField;
        
        private string nameField;
        
        private string slotTypeField;
        
        /// <remarks/>
        public ValueListType ValueList {
            get {
                return this.valueListField;
            }
            set {
                this.valueListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string slotType {
            get {
                return this.slotTypeField;
            }
            set {
                this.slotTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0")]
    public partial class RegistryResponseType {
        
        private SlotType1[] responseSlotListField;
        
        private RegistryErrorList registryErrorListField;
        
        private string statusField;
        
        private string requestIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Slot", Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0", IsNullable=false)]
        public SlotType1[] ResponseSlotList {
            get {
                return this.responseSlotListField;
            }
            set {
                this.responseSlotListField = value;
            }
        }
        
        /// <remarks/>
        public RegistryErrorList RegistryErrorList {
            get {
                return this.registryErrorListField;
            }
            set {
                this.registryErrorListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0")]
    public partial class RegistryErrorList {
        
        private RegistryError[] registryErrorField;
        
        private string highestSeverityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RegistryError")]
        public RegistryError[] RegistryError {
            get {
                return this.registryErrorField;
            }
            set {
                this.registryErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string highestSeverity {
            get {
                return this.highestSeverityField;
            }
            set {
                this.highestSeverityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0")]
    public partial class RegistryError {
        
        private string codeContextField;
        
        private string errorCodeField;
        
        private string severityField;
        
        private string locationField;
        
        private string valueField;
        
        public RegistryError() {
            this.severityField = "urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codeContext {
            get {
                return this.codeContextField;
            }
            set {
                this.codeContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        [System.ComponentModel.DefaultValueAttribute("urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error")]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ihe:iti:xds-b:2007")]
    public partial class RetrieveDocumentSetResponseType {
        
        private RegistryResponseType registryResponseField;
        
        private RetrieveDocumentSetResponseTypeDocumentResponse[] documentResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0")]
        public RegistryResponseType RegistryResponse {
            get {
                return this.registryResponseField;
            }
            set {
                this.registryResponseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DocumentResponse")]
        public RetrieveDocumentSetResponseTypeDocumentResponse[] DocumentResponse {
            get {
                return this.documentResponseField;
            }
            set {
                this.documentResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ihe:iti:xds-b:2007")]
    public partial class RetrieveDocumentSetResponseTypeDocumentResponse {
        
        private string homeCommunityIdField;
        
        private string repositoryUniqueIdField;
        
        private string documentUniqueIdField;
        
        private string mimeTypeField;
        
        private byte[] documentField;
        
        /// <remarks/>
        public string HomeCommunityId {
            get {
                return this.homeCommunityIdField;
            }
            set {
                this.homeCommunityIdField = value;
            }
        }
        
        /// <remarks/>
        public string RepositoryUniqueId {
            get {
                return this.repositoryUniqueIdField;
            }
            set {
                this.repositoryUniqueIdField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentUniqueId {
            get {
                return this.documentUniqueIdField;
            }
            set {
                this.documentUniqueIdField = value;
            }
        }
        
        /// <remarks/>
        public string mimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class NhinTargetCommunityType {
        
        private HomeCommunityType homeCommunityField;
        
        private string listField;
        
        private string regionField;
        
        /// <remarks/>
        public HomeCommunityType homeCommunity {
            get {
                return this.homeCommunityField;
            }
            set {
                this.homeCommunityField = value;
            }
        }
        
        /// <remarks/>
        public string list {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
            }
        }
        
        /// <remarks/>
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class HomeCommunityType {
        
        private string descriptionField;
        
        private string homeCommunityIdField;
        
        private string nameField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string homeCommunityId {
            get {
                return this.homeCommunityIdField;
            }
            set {
                this.homeCommunityIdField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class SamlSignatureKeyInfoType {
        
        private byte[] rsaKeyValueModulusField;
        
        private byte[] rsaKeyValueExponentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] rsaKeyValueModulus {
            get {
                return this.rsaKeyValueModulusField;
            }
            set {
                this.rsaKeyValueModulusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] rsaKeyValueExponent {
            get {
                return this.rsaKeyValueExponentField;
            }
            set {
                this.rsaKeyValueExponentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class SamlSignatureType {
        
        private SamlSignatureKeyInfoType keyInfoField;
        
        private byte[] signatureValueField;
        
        /// <remarks/>
        public SamlSignatureKeyInfoType keyInfo {
            get {
                return this.keyInfoField;
            }
            set {
                this.keyInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] signatureValue {
            get {
                return this.signatureValueField;
            }
            set {
                this.signatureValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class SamlAuthzDecisionStatementEvidenceConditionsType {
        
        private string notBeforeField;
        
        private string notOnOrAfterField;
        
        /// <remarks/>
        public string notBefore {
            get {
                return this.notBeforeField;
            }
            set {
                this.notBeforeField = value;
            }
        }
        
        /// <remarks/>
        public string notOnOrAfter {
            get {
                return this.notOnOrAfterField;
            }
            set {
                this.notOnOrAfterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class SamlAuthzDecisionStatementEvidenceAssertionType {
        
        private string idField;
        
        private string issueInstantField;
        
        private string versionField;
        
        private string issuerField;
        
        private string issuerFormatField;
        
        private SamlAuthzDecisionStatementEvidenceConditionsType conditionsField;
        
        private string accessConsentPolicyField;
        
        private string instanceAccessConsentPolicyField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string issueInstant {
            get {
                return this.issueInstantField;
            }
            set {
                this.issueInstantField = value;
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string issuer {
            get {
                return this.issuerField;
            }
            set {
                this.issuerField = value;
            }
        }
        
        /// <remarks/>
        public string issuerFormat {
            get {
                return this.issuerFormatField;
            }
            set {
                this.issuerFormatField = value;
            }
        }
        
        /// <remarks/>
        public SamlAuthzDecisionStatementEvidenceConditionsType conditions {
            get {
                return this.conditionsField;
            }
            set {
                this.conditionsField = value;
            }
        }
        
        /// <remarks/>
        public string accessConsentPolicy {
            get {
                return this.accessConsentPolicyField;
            }
            set {
                this.accessConsentPolicyField = value;
            }
        }
        
        /// <remarks/>
        public string instanceAccessConsentPolicy {
            get {
                return this.instanceAccessConsentPolicyField;
            }
            set {
                this.instanceAccessConsentPolicyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class SamlAuthzDecisionStatementEvidenceType {
        
        private SamlAuthzDecisionStatementEvidenceAssertionType assertionField;
        
        /// <remarks/>
        public SamlAuthzDecisionStatementEvidenceAssertionType assertion {
            get {
                return this.assertionField;
            }
            set {
                this.assertionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class SamlAuthzDecisionStatementType {
        
        private string decisionField;
        
        private string resourceField;
        
        private string actionField;
        
        private SamlAuthzDecisionStatementEvidenceType evidenceField;
        
        /// <remarks/>
        public string decision {
            get {
                return this.decisionField;
            }
            set {
                this.decisionField = value;
            }
        }
        
        /// <remarks/>
        public string resource {
            get {
                return this.resourceField;
            }
            set {
                this.resourceField = value;
            }
        }
        
        /// <remarks/>
        public string action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        public SamlAuthzDecisionStatementEvidenceType evidence {
            get {
                return this.evidenceField;
            }
            set {
                this.evidenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class SamlAuthnStatementType {
        
        private string authInstantField;
        
        private string sessionIndexField;
        
        private string authContextClassRefField;
        
        private string subjectLocalityAddressField;
        
        private string subjectLocalityDNSNameField;
        
        /// <remarks/>
        public string authInstant {
            get {
                return this.authInstantField;
            }
            set {
                this.authInstantField = value;
            }
        }
        
        /// <remarks/>
        public string sessionIndex {
            get {
                return this.sessionIndexField;
            }
            set {
                this.sessionIndexField = value;
            }
        }
        
        /// <remarks/>
        public string authContextClassRef {
            get {
                return this.authContextClassRefField;
            }
            set {
                this.authContextClassRefField = value;
            }
        }
        
        /// <remarks/>
        public string subjectLocalityAddress {
            get {
                return this.subjectLocalityAddressField;
            }
            set {
                this.subjectLocalityAddressField = value;
            }
        }
        
        /// <remarks/>
        public string subjectLocalityDNSName {
            get {
                return this.subjectLocalityDNSNameField;
            }
            set {
                this.subjectLocalityDNSNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class UserType {
        
        private PersonNameType personNameField;
        
        private string userNameField;
        
        private HomeCommunityType orgField;
        
        private CeType roleCodedField;
        
        /// <remarks/>
        public PersonNameType personName {
            get {
                return this.personNameField;
            }
            set {
                this.personNameField = value;
            }
        }
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public HomeCommunityType org {
            get {
                return this.orgField;
            }
            set {
                this.orgField = value;
            }
        }
        
        /// <remarks/>
        public CeType roleCoded {
            get {
                return this.roleCodedField;
            }
            set {
                this.roleCodedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class PersonNameType {
        
        private string familyNameField;
        
        private string givenNameField;
        
        private CeType nameTypeField;
        
        private string secondNameOrInitialsField;
        
        private string fullNameField;
        
        private string prefixField;
        
        private string suffixField;
        
        /// <remarks/>
        public string familyName {
            get {
                return this.familyNameField;
            }
            set {
                this.familyNameField = value;
            }
        }
        
        /// <remarks/>
        public string givenName {
            get {
                return this.givenNameField;
            }
            set {
                this.givenNameField = value;
            }
        }
        
        /// <remarks/>
        public CeType nameType {
            get {
                return this.nameTypeField;
            }
            set {
                this.nameTypeField = value;
            }
        }
        
        /// <remarks/>
        public string secondNameOrInitials {
            get {
                return this.secondNameOrInitialsField;
            }
            set {
                this.secondNameOrInitialsField = value;
            }
        }
        
        /// <remarks/>
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public string prefix {
            get {
                return this.prefixField;
            }
            set {
                this.prefixField = value;
            }
        }
        
        /// <remarks/>
        public string suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class CeType {
        
        private string codeField;
        
        private string codeSystemField;
        
        private string codeSystemNameField;
        
        private string codeSystemVersionField;
        
        private string displayNameField;
        
        private string originalTextField;
        
        private CeType[] translationField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string codeSystem {
            get {
                return this.codeSystemField;
            }
            set {
                this.codeSystemField = value;
            }
        }
        
        /// <remarks/>
        public string codeSystemName {
            get {
                return this.codeSystemNameField;
            }
            set {
                this.codeSystemNameField = value;
            }
        }
        
        /// <remarks/>
        public string codeSystemVersion {
            get {
                return this.codeSystemVersionField;
            }
            set {
                this.codeSystemVersionField = value;
            }
        }
        
        /// <remarks/>
        public string displayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string originalText {
            get {
                return this.originalTextField;
            }
            set {
                this.originalTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("translation")]
        public CeType[] translation {
            get {
                return this.translationField;
            }
            set {
                this.translationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class PhoneType {
        
        private string areaCodeField;
        
        private string countryCodeField;
        
        private string extensionField;
        
        private string localNumberField;
        
        private CeType phoneNumberTypeField;
        
        /// <remarks/>
        public string areaCode {
            get {
                return this.areaCodeField;
            }
            set {
                this.areaCodeField = value;
            }
        }
        
        /// <remarks/>
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        public string localNumber {
            get {
                return this.localNumberField;
            }
            set {
                this.localNumberField = value;
            }
        }
        
        /// <remarks/>
        public CeType phoneNumberType {
            get {
                return this.phoneNumberTypeField;
            }
            set {
                this.phoneNumberTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class AddressType {
        
        private CeType addressTypeField;
        
        private string cityField;
        
        private string countryField;
        
        private string stateField;
        
        private string streetAddressField;
        
        private string zipCodeField;
        
        /// <remarks/>
        public CeType addressType {
            get {
                return this.addressTypeField;
            }
            set {
                this.addressTypeField = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string streetAddress {
            get {
                return this.streetAddressField;
            }
            set {
                this.streetAddressField = value;
            }
        }
        
        /// <remarks/>
        public string zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gov:hhs:fha:nhinc:common:nhinccommon")]
    public partial class AssertionType {
        
        private AddressType addressField;
        
        private string dateOfBirthField;
        
        private string explanationNonClaimantSignatureField;
        
        private bool haveSecondWitnessSignatureField;
        
        private bool haveSignatureField;
        
        private bool haveWitnessSignatureField;
        
        private HomeCommunityType homeCommunityField;
        
        private PersonNameType personNameField;
        
        private PhoneType phoneNumberField;
        
        private AddressType secondWitnessAddressField;
        
        private PersonNameType secondWitnessNameField;
        
        private PhoneType secondWitnessPhoneField;
        
        private string sSNField;
        
        private string[] uniquePatientIdField;
        
        private AddressType witnessAddressField;
        
        private PersonNameType witnessNameField;
        
        private PhoneType witnessPhoneField;
        
        private UserType userInfoField;
        
        private bool authorizedField;
        
        private CeType purposeOfDisclosureCodedField;
        
        private SamlAuthnStatementType samlAuthnStatementField;
        
        private SamlAuthzDecisionStatementType samlAuthzDecisionStatementField;
        
        private SamlSignatureType samlSignatureField;
        
        private string messageIdField;
        
        private string[] relatesToListField;
        
        /// <remarks/>
        public AddressType address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string dateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string explanationNonClaimantSignature {
            get {
                return this.explanationNonClaimantSignatureField;
            }
            set {
                this.explanationNonClaimantSignatureField = value;
            }
        }
        
        /// <remarks/>
        public bool haveSecondWitnessSignature {
            get {
                return this.haveSecondWitnessSignatureField;
            }
            set {
                this.haveSecondWitnessSignatureField = value;
            }
        }
        
        /// <remarks/>
        public bool haveSignature {
            get {
                return this.haveSignatureField;
            }
            set {
                this.haveSignatureField = value;
            }
        }
        
        /// <remarks/>
        public bool haveWitnessSignature {
            get {
                return this.haveWitnessSignatureField;
            }
            set {
                this.haveWitnessSignatureField = value;
            }
        }
        
        /// <remarks/>
        public HomeCommunityType homeCommunity {
            get {
                return this.homeCommunityField;
            }
            set {
                this.homeCommunityField = value;
            }
        }
        
        /// <remarks/>
        public PersonNameType personName {
            get {
                return this.personNameField;
            }
            set {
                this.personNameField = value;
            }
        }
        
        /// <remarks/>
        public PhoneType phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public AddressType secondWitnessAddress {
            get {
                return this.secondWitnessAddressField;
            }
            set {
                this.secondWitnessAddressField = value;
            }
        }
        
        /// <remarks/>
        public PersonNameType secondWitnessName {
            get {
                return this.secondWitnessNameField;
            }
            set {
                this.secondWitnessNameField = value;
            }
        }
        
        /// <remarks/>
        public PhoneType secondWitnessPhone {
            get {
                return this.secondWitnessPhoneField;
            }
            set {
                this.secondWitnessPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string SSN {
            get {
                return this.sSNField;
            }
            set {
                this.sSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("uniquePatientId")]
        public string[] uniquePatientId {
            get {
                return this.uniquePatientIdField;
            }
            set {
                this.uniquePatientIdField = value;
            }
        }
        
        /// <remarks/>
        public AddressType witnessAddress {
            get {
                return this.witnessAddressField;
            }
            set {
                this.witnessAddressField = value;
            }
        }
        
        /// <remarks/>
        public PersonNameType witnessName {
            get {
                return this.witnessNameField;
            }
            set {
                this.witnessNameField = value;
            }
        }
        
        /// <remarks/>
        public PhoneType witnessPhone {
            get {
                return this.witnessPhoneField;
            }
            set {
                this.witnessPhoneField = value;
            }
        }
        
        /// <remarks/>
        public UserType userInfo {
            get {
                return this.userInfoField;
            }
            set {
                this.userInfoField = value;
            }
        }
        
        /// <remarks/>
        public bool authorized {
            get {
                return this.authorizedField;
            }
            set {
                this.authorizedField = value;
            }
        }
        
        /// <remarks/>
        public CeType purposeOfDisclosureCoded {
            get {
                return this.purposeOfDisclosureCodedField;
            }
            set {
                this.purposeOfDisclosureCodedField = value;
            }
        }
        
        /// <remarks/>
        public SamlAuthnStatementType samlAuthnStatement {
            get {
                return this.samlAuthnStatementField;
            }
            set {
                this.samlAuthnStatementField = value;
            }
        }
        
        /// <remarks/>
        public SamlAuthzDecisionStatementType samlAuthzDecisionStatement {
            get {
                return this.samlAuthzDecisionStatementField;
            }
            set {
                this.samlAuthzDecisionStatementField = value;
            }
        }
        
        /// <remarks/>
        public SamlSignatureType samlSignature {
            get {
                return this.samlSignatureField;
            }
            set {
                this.samlSignatureField = value;
            }
        }
        
        /// <remarks/>
        public string messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("relatesToList")]
        public string[] relatesToList {
            get {
                return this.relatesToListField;
            }
            set {
                this.relatesToListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void RespondingGateway_CrossGatewayRetrieveCompletedEventHandler(object sender, RespondingGateway_CrossGatewayRetrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RespondingGateway_CrossGatewayRetrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RespondingGateway_CrossGatewayRetrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetrieveDocumentSetResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetrieveDocumentSetResponseType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591