//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobius.CoreLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MobiusError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MobiusError() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mobius.CoreLibrary.MobiusError", typeof(MobiusError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accomplish date should not be less than today..
        /// </summary>
        public static string Accomplish_Date_Should_Not_Be_Less_Than_Today {
            get {
                return ResourceManager.GetString("Accomplish_Date_Should_Not_Be_Less_Than_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is expired..
        /// </summary>
        public static string Account_Expired {
            get {
                return ResourceManager.GetString("Account_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account can be upgraded within {0} days of expiration date.  Please verify the expiration date/time..
        /// </summary>
        public static string Account_Upgradation_Error_Message {
            get {
                return ResourceManager.GetString("Account_Upgradation_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account upgradation failed..
        /// </summary>
        public static string Account_Upgradation_Failed {
            get {
                return ResourceManager.GetString("Account_Upgradation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account has been successfully upgraded and is valid till {0}..
        /// </summary>
        public static string Account_Upgraded_Successfully {
            get {
                return ResourceManager.GetString("Account_Upgraded_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledgement sent successfully.
        /// </summary>
        public static string Acknowledgement_Sent_Successfully {
            get {
                return ResourceManager.GetString("Acknowledgement_Sent_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been sent to system administrator for activation..
        /// </summary>
        public static string Activation_In_Process {
            get {
                return ResourceManager.GetString("Activation_In_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address has some special characters..
        /// </summary>
        public static string Address_Has_SpecialCharacater {
            get {
                return ResourceManager.GetString("Address_Has_SpecialCharacater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed. Communit(y|ies):{0} already exist..
        /// </summary>
        public static string All_Exist_Records_Not_Imported {
            get {
                return ResourceManager.GetString("All_Exist_Records_Not_Imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment date should not be less than today..
        /// </summary>
        public static string Appointment_Date_Should_Not_Be_Less_Than_Today {
            get {
                return ResourceManager.GetString("Appointment_Date_Should_Not_Be_Less_Than_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or empty assertion object..
        /// </summary>
        public static string Assertion_Object_Invalid {
            get {
                return ResourceManager.GetString("Assertion_Object_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required values to form assertion, like user information, user role, purpose of use, home community etc. is missing. Please verify..
        /// </summary>
        public static string Assertion_Required_Information_Missing {
            get {
                return ResourceManager.GetString("Assertion_Required_Information_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document validation failed. Not a valid C32 document..
        /// </summary>
        public static string C32Document_Validation_Failed {
            get {
                return ResourceManager.GetString("C32Document_Validation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C32 Document sections are missing.
        /// </summary>
        public static string C32Sections_Missing {
            get {
                return ResourceManager.GetString("C32Sections_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User preferences doesn&apos;t allow this action to be completed. Please enable &apos;Allow other devices&apos; option from the registered device..
        /// </summary>
        public static string Certificate_Data_Missing {
            get {
                return ResourceManager.GetString("Certificate_Data_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account upgraded successfully. However old certificate could not be removed..
        /// </summary>
        public static string Certificate_Deletion_Failed {
            get {
                return ResourceManager.GetString("Certificate_Deletion_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing of user details has been failed..
        /// </summary>
        public static string Certificate_Export_Failed {
            get {
                return ResourceManager.GetString("Certificate_Export_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSR not provided..
        /// </summary>
        public static string CertificateAuthority_CSR_Missing {
            get {
                return ResourceManager.GetString("CertificateAuthority_CSR_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate request fail.
        /// </summary>
        public static string CertificateAuthority_Enrollment_Fail {
            get {
                return ResourceManager.GetString("CertificateAuthority_Enrollment_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate request is pending..
        /// </summary>
        public static string CertificateAuthority_Enrollment_Pending {
            get {
                return ResourceManager.GetString("CertificateAuthority_Enrollment_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate issuer name is mismatch..
        /// </summary>
        public static string CertificateAuthority_Validate_CAIssuerName_Mismatch {
            get {
                return ResourceManager.GetString("CertificateAuthority_Validate_CAIssuerName_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate is expired..
        /// </summary>
        public static string CertificateAuthority_Validate_Certificate_Expired {
            get {
                return ResourceManager.GetString("CertificateAuthority_Validate_Certificate_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate information is missing..
        /// </summary>
        public static string CertificateAuthority_Validate_Certificate_Missing {
            get {
                return ResourceManager.GetString("CertificateAuthority_Validate_Certificate_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password has been generated and send to you on registered email Id..
        /// </summary>
        public static string CheckEmailForNewPassword {
            get {
                return ResourceManager.GetString("CheckEmailForNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is not provided..
        /// </summary>
        public static string City_Is_Missing {
            get {
                return ResourceManager.GetString("City_Is_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Description is Missing..
        /// </summary>
        public static string Community_Description_Missing {
            get {
                return ResourceManager.GetString("Community_Description_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Identifier is Missing..
        /// </summary>
        public static string Community_Identifier_Missing {
            get {
                return ResourceManager.GetString("Community_Identifier_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consent Directive already mapped for the combination of role and purpose. Please update the existing record..
        /// </summary>
        public static string CONSENT_DIRECTIVE_ALREADY_MAPPED {
            get {
                return ResourceManager.GetString("CONSENT_DIRECTIVE_ALREADY_MAPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Consent Failed.
        /// </summary>
        public static string CONSENT_FAILED {
            get {
                return ResourceManager.GetString("CONSENT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is not provided..
        /// </summary>
        public static string Country_Is_Missing {
            get {
                return ResourceManager.GetString("Country_Is_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth should be before or equal to current date..
        /// </summary>
        public static string DOB_Can_Not_Be_Greater_Than_Current {
            get {
                return ResourceManager.GetString("DOB_Can_Not_Be_Greater_Than_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth is not provided..
        /// </summary>
        public static string DOB_Not_Provided {
            get {
                return ResourceManager.GetString("DOB_Not_Provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document byte is missing..
        /// </summary>
        public static string Document_Byte_Missing {
            get {
                return ResourceManager.GetString("Document_Byte_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommunityId not specified..
        /// </summary>
        public static string Document_communityId_Missing {
            get {
                return ResourceManager.GetString("Document_communityId_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentId not provided.
        /// </summary>
        public static string Document_DocumentId_Missing {
            get {
                return ResourceManager.GetString("Document_DocumentId_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document gateway response has an error..
        /// </summary>
        public static string Document_GateWayResponse_Error {
            get {
                return ResourceManager.GetString("Document_GateWayResponse_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document PatientId missing.
        /// </summary>
        public static string Document_PatientId_Missing {
            get {
                return ResourceManager.GetString("Document_PatientId_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose not provided.
        /// </summary>
        public static string Document_Purpose_Missing {
            get {
                return ResourceManager.GetString("Document_Purpose_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceRepositoryId not provided..
        /// </summary>
        public static string Document_SourceRepositoryId_Missing {
            get {
                return ResourceManager.GetString("Document_SourceRepositoryId_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject not provided..
        /// </summary>
        public static string Document_Subject_Missing {
            get {
                return ResourceManager.GetString("Document_Subject_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document submission failed.
        /// </summary>
        public static string DocumentSubmissionFailed {
            get {
                return ResourceManager.GetString("DocumentSubmissionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a duplicate entry. Please verify..
        /// </summary>
        public static string Duplicate_Entry {
            get {
                return ResourceManager.GetString("Duplicate_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id is missing..
        /// </summary>
        public static string EmailAddress_Missing {
            get {
                return ResourceManager.GetString("EmailAddress_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in emergency access.
        /// </summary>
        public static string Error_in_emergency_access {
            get {
                return ResourceManager.GetString("Error_in_emergency_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in updating audit status..
        /// </summary>
        public static string Error_in_updating_audit_status {
            get {
                return ResourceManager.GetString("Error_in_updating_audit_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred in C32 Document parsing.
        /// </summary>
        public static string ErrorOccurredInC32Document_Parsing {
            get {
                return ResourceManager.GetString("ErrorOccurredInC32Document_Parsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorSuccess.
        /// </summary>
        public static string ErrorSuccess {
            get {
                return ResourceManager.GetString("ErrorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some errors occurred while processing..
        /// </summary>
        public static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FacilityId not provided..
        /// </summary>
        public static string FacilityId_Missing {
            get {
                return ResourceManager.GetString("FacilityId_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record does not exists.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender not provided..
        /// </summary>
        public static string Gender_Not_Provided {
            get {
                return ResourceManager.GetString("Gender_Not_Provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record can&apos;t be deleted, as it is the Home Community..
        /// </summary>
        public static string HomeCommunity_Deletion_Failed {
            get {
                return ResourceManager.GetString("HomeCommunity_Deletion_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed, as account is inactive. .
        /// </summary>
        public static string Inactive_Account {
            get {
                return ResourceManager.GetString("Inactive_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid old password..
        /// </summary>
        public static string Incorrect_Old_Password {
            get {
                return ResourceManager.GetString("Incorrect_Old_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invaid login credential..
        /// </summary>
        public static string InvaidLoginCredential {
            get {
                return ResourceManager.GetString("InvaidLoginCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either Patient Id or communityId is invalid..
        /// </summary>
        public static string InvaidPatientIdOrCommunityId {
            get {
                return ResourceManager.GetString("InvaidPatientIdOrCommunityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide valid address..
        /// </summary>
        public static string Invalid_Address {
            get {
                return ResourceManager.GetString("Invalid_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Communities.
        /// </summary>
        public static string Invalid_Communities {
            get {
                return ResourceManager.GetString("Invalid_Communities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date format.Please provide date in mm/dd/yyyy format..
        /// </summary>
        public static string Invalid_Date_Format {
            get {
                return ResourceManager.GetString("Invalid_Date_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email Id..
        /// </summary>
        public static string Invalid_Email_Address {
            get {
                return ResourceManager.GetString("Invalid_Email_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension number must be numeric and less than or equal to six (6) digit..
        /// </summary>
        public static string Invalid_Extension_Format {
            get {
                return ResourceManager.GetString("Invalid_Extension_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file does not reflect the desired format as mentioned in the Column map section in the page. Download the template and use the same..
        /// </summary>
        public static string Invalid_File_Format {
            get {
                return ResourceManager.GetString("Invalid_File_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must use a combination of these: atleast one upper case, Lower case, atleast one number,atleast one non-alphanumeric and at least 8 characters..
        /// </summary>
        public static string Invalid_Password {
            get {
                return ResourceManager.GetString("Invalid_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide phone number in the following format:###-###-#### or ########## or #-###-###-#### or (###) ###-####.
        /// </summary>
        public static string Invalid_Phone_Format {
            get {
                return ResourceManager.GetString("Invalid_Phone_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid Postal Code.
        /// </summary>
        public static string Invalid_Postal_Code {
            get {
                return ResourceManager.GetString("Invalid_Postal_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote community Id is missing..
        /// </summary>
        public static string Invalid_RemoteCommunityId {
            get {
                return ResourceManager.GetString("Invalid_RemoteCommunityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote PatientId is misssing..
        /// </summary>
        public static string Invalid_RemotePatientID {
            get {
                return ResourceManager.GetString("Invalid_RemotePatientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response data.
        /// </summary>
        public static string Invalid_Response_Data {
            get {
                return ResourceManager.GetString("Invalid_Response_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the SSN in the following format ###-##-#### or #########.
        /// </summary>
        public static string Invalid_SSN {
            get {
                return ResourceManager.GetString("Invalid_SSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid URL.
        /// </summary>
        public static string Invalid_URI {
            get {
                return ResourceManager.GetString("Invalid_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset failed..
        /// </summary>
        public static string Invalid_UserId {
            get {
                return ResourceManager.GetString("Invalid_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided user type is invalid..
        /// </summary>
        public static string Invalid_UserType {
            get {
                return ResourceManager.GetString("Invalid_UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid validation specificationId.
        /// </summary>
        public static string Invalid_Validation_SpecificationId {
            get {
                return ResourceManager.GetString("Invalid_Validation_SpecificationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PatientId is invalid..
        /// </summary>
        public static string InvalidPatientId {
            get {
                return ResourceManager.GetString("InvalidPatientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either email ID, password or user type is incorrect..
        /// </summary>
        public static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommunityId is missing.
        /// </summary>
        public static string MissingCommunityId {
            get {
                return ResourceManager.GetString("MissingCommunityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing input parameters..
        /// </summary>
        public static string MissingParameters {
            get {
                return ResourceManager.GetString("MissingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PatientId is missing .
        /// </summary>
        public static string MissingPatientId {
            get {
                return ResourceManager.GetString("MissingPatientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters found in mother maiden name..
        /// </summary>
        public static string MothersMaidenName_Contains_Specialcharacater {
            get {
                return ResourceManager.GetString("MothersMaidenName_Contains_Specialcharacater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify Mother&apos;s maiden name for further filtration of records..
        /// </summary>
        public static string MothersMaidenNameRequested {
            get {
                return ResourceManager.GetString("MothersMaidenNameRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters found in name..
        /// </summary>
        public static string Name_Contains_Specialcharacater {
            get {
                return ResourceManager.GetString("Name_Contains_Specialcharacater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is not provided..
        /// </summary>
        public static string New_Password_Missing {
            get {
                return ResourceManager.GetString("New_Password_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record to display.
        /// </summary>
        public static string No_Record_To_Display {
            get {
                return ResourceManager.GetString("No_Record_To_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Result Found.
        /// </summary>
        public static string No_Result_Found {
            get {
                return ResourceManager.GetString("No_Result_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Document Found.
        /// </summary>
        public static string NODOCUMENTFOUND {
            get {
                return ResourceManager.GetString("NODOCUMENTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not  Authenticated Certificate.
        /// </summary>
        public static string Not_Authenticated_Certificate_ {
            get {
                return ResourceManager.GetString("Not_Authenticated_Certificate_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid certificate.
        /// </summary>
        public static string Not_Valid_Certificate {
            get {
                return ResourceManager.GetString("Not_Valid_Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request data is not valid.
        /// </summary>
        public static string Not_Valid_Request_Data {
            get {
                return ResourceManager.GetString("Not_Valid_Request_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response  data is not valid.
        /// </summary>
        public static string Not_Valid_Response_Data {
            get {
                return ResourceManager.GetString("Not_Valid_Response_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is not provided..
        /// </summary>
        public static string Old_Password_Missing {
            get {
                return ResourceManager.GetString("Old_Password_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password and new password are same..
        /// </summary>
        public static string OldPassword_And_NewPassword_Equal {
            get {
                return ResourceManager.GetString("OldPassword_And_NewPassword_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide street details..
        /// </summary>
        public static string One_Address_Is_Required {
            get {
                return ResourceManager.GetString("One_Address_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully..
        /// </summary>
        public static string Password_Change_Successfull {
            get {
                return ResourceManager.GetString("Password_Change_Successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password  is missing.
        /// </summary>
        public static string Password_Missing {
            get {
                return ResourceManager.GetString("Password_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset failed..
        /// </summary>
        public static string Password_Reset_Failed {
            get {
                return ResourceManager.GetString("Password_Reset_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient already exists.
        /// </summary>
        public static string patient_Allready_Exist {
            get {
                return ResourceManager.GetString("patient_Allready_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consent already exists..
        /// </summary>
        public static string patient_Consent_Already_Exists {
            get {
                return ResourceManager.GetString("patient_Consent_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider doesn&apos;t have sufficient permission..
        /// </summary>
        public static string Patient_Consent_Deviated {
            get {
                return ResourceManager.GetString("Patient_Consent_Deviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient consent is missing..
        /// </summary>
        public static string Patient_Consent_Does_Not_Exist {
            get {
                return ResourceManager.GetString("Patient_Consent_Does_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient consent Id is missing..
        /// </summary>
        public static string patient_Consent_ID {
            get {
                return ResourceManager.GetString("patient_Consent_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consent not mapped for patient {0}. Fail to share..
        /// </summary>
        public static string Patient_Consent_Missing {
            get {
                return ResourceManager.GetString("Patient_Consent_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient details not found..
        /// </summary>
        public static string Patient_Details_Not_Found {
            get {
                return ResourceManager.GetString("Patient_Details_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient first name is missing..
        /// </summary>
        public static string Patient_First_Name_Missing {
            get {
                return ResourceManager.GetString("Patient_First_Name_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient last name is missing..
        /// </summary>
        public static string Patient_Last_Name_Missing {
            get {
                return ResourceManager.GetString("Patient_Last_Name_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient MPIID is not provided..
        /// </summary>
        public static string patient_MPIID_Missing {
            get {
                return ResourceManager.GetString("patient_MPIID_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient referred successfully.
        /// </summary>
        public static string Patient_Referred_Successfully {
            get {
                return ResourceManager.GetString("Patient_Referred_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient registered successfully..
        /// </summary>
        public static string patient_Registration_successful {
            get {
                return ResourceManager.GetString("patient_Registration_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient details updated successfully..
        /// </summary>
        public static string Patient_Updated {
            get {
                return ResourceManager.GetString("Patient_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify patient address fields..
        /// </summary>
        public static string PatientAdressRequested {
            get {
                return ResourceManager.GetString("PatientAdressRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occur while fetching Patient Correlation..
        /// </summary>
        public static string PatientCorrelationError {
            get {
                return ResourceManager.GetString("PatientCorrelationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient appointment date is not provided..
        /// </summary>
        public static string PatientReferral_Appointment_Date {
            get {
                return ResourceManager.GetString("PatientReferral_Appointment_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document not provided.
        /// </summary>
        public static string PatientReferral_Document_Missing {
            get {
                return ResourceManager.GetString("PatientReferral_Document_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Referral not created..
        /// </summary>
        public static string PatientReferral_Failed {
            get {
                return ResourceManager.GetString("PatientReferral_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email Id..
        /// </summary>
        public static string PatientReferral_InValid_ReferralEmailAddress {
            get {
                return ResourceManager.GetString("PatientReferral_InValid_ReferralEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient information is not provided.
        /// </summary>
        public static string PatientReferral_Patient_Information_Missing {
            get {
                return ResourceManager.GetString("PatientReferral_Patient_Information_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral accomplished date is not provided..
        /// </summary>
        public static string PatientReferral_ReferralOn {
            get {
                return ResourceManager.GetString("PatientReferral_ReferralOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the patient information is missing.
        /// </summary>
        public static string PatientReferral_Some_Of_Patient_Information_Missing {
            get {
                return ResourceManager.GetString("PatientReferral_Some_Of_Patient_Information_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify patient telephone number..
        /// </summary>
        public static string PatientTelecomRequested {
            get {
                return ResourceManager.GetString("PatientTelecomRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission(s) and Category(s) have been successfully created..
        /// </summary>
        public static string PERMISSION_CATEGORY_SUCCESSFULLY_CREATED {
            get {
                return ResourceManager.GetString("PERMISSION_CATEGORY_SUCCESSFULLY_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission(s) and Category(s) have been successfully updated..
        /// </summary>
        public static string PERMISSION_CATEGORY_SUCCESSFULLY_UPDATED {
            get {
                return ResourceManager.GetString("PERMISSION_CATEGORY_SUCCESSFULLY_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate bytes missing..
        /// </summary>
        public static string PFX_Certificate_Not_Found {
            get {
                return ResourceManager.GetString("PFX_Certificate_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy submission failed.
        /// </summary>
        public static string PolicySubmissionFailed {
            get {
                return ResourceManager.GetString("PolicySubmissionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider already exists..
        /// </summary>
        public static string Provider_Already_Exist {
            get {
                return ResourceManager.GetString("Provider_Already_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider cannot make a referral to himself.
        /// </summary>
        public static string Provider_Cannot_Make_A_Referral_To_Himself {
            get {
                return ResourceManager.GetString("Provider_Cannot_Make_A_Referral_To_Himself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider details not found..
        /// </summary>
        public static string Provider_Details_Not_Found {
            get {
                return ResourceManager.GetString("Provider_Details_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider does not have sufficient permission to view the document..
        /// </summary>
        public static string Provider_Doesnot_Have_Permission_ToView {
            get {
                return ResourceManager.GetString("Provider_Doesnot_Have_Permission_ToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id not provided..
        /// </summary>
        public static string Provider_Email_Address_Missing {
            get {
                return ResourceManager.GetString("Provider_Email_Address_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name not provided..
        /// </summary>
        public static string Provider_First_Name_Missing {
            get {
                return ResourceManager.GetString("Provider_First_Name_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email Id..
        /// </summary>
        public static string Provider_Invalid_Email {
            get {
                return ResourceManager.GetString("Provider_Invalid_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name not provided..
        /// </summary>
        public static string Provider_Last_Name_Missing {
            get {
                return ResourceManager.GetString("Provider_Last_Name_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical records delivery email Id is not provided..
        /// </summary>
        public static string Provider_MedicalRecordsDeliveryEmailAddress_Missing {
            get {
                return ResourceManager.GetString("Provider_MedicalRecordsDeliveryEmailAddress_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization name not provided..
        /// </summary>
        public static string Provider_Organization_Name_Missing {
            get {
                return ResourceManager.GetString("Provider_Organization_Name_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider registration failed..
        /// </summary>
        public static string Provider_Registration_Failed {
            get {
                return ResourceManager.GetString("Provider_Registration_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider registered successfully..
        /// </summary>
        public static string Provider_Registration_successful {
            get {
                return ResourceManager.GetString("Provider_Registration_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider type not provided..
        /// </summary>
        public static string Provider_Type {
            get {
                return ResourceManager.GetString("Provider_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose of use is missing..
        /// </summary>
        public static string PurposeOf_UseId_Missing {
            get {
                return ResourceManager.GetString("PurposeOf_UseId_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record updated successfully..
        /// </summary>
        public static string Record_Successfully_Updated {
            get {
                return ResourceManager.GetString("Record_Successfully_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Not Found.
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records imported successfully..
        /// </summary>
        public static string Records_Imported_Successfully {
            get {
                return ResourceManager.GetString("Records_Imported_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral has been completed and the document has been sent to the requestor.
        /// </summary>
        public static string Referral_Completed {
            get {
                return ResourceManager.GetString("Referral_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral out come document missing.
        /// </summary>
        public static string Referral_Out_Come_Document_Missing {
            get {
                return ResourceManager.GetString("Referral_Out_Come_Document_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome Document missing.
        /// </summary>
        public static string Referral_Outcome_Document_Missing {
            get {
                return ResourceManager.GetString("Referral_Outcome_Document_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient appointment date cannot be set to a date after referral accomplishment date..
        /// </summary>
        public static string ReferralAccomplishedDate_GreaterThan_ReferralDate {
            get {
                return ResourceManager.GetString("ReferralAccomplishedDate_GreaterThan_ReferralDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository ID is missing..
        /// </summary>
        public static string RepositoryId_Missing {
            get {
                return ResourceManager.GetString("RepositoryId_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User type is missing..
        /// </summary>
        public static string Role_ID {
            get {
                return ResourceManager.GetString("Role_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule end date is not provided..
        /// </summary>
        public static string RuleEnd_Date_Missing {
            get {
                return ResourceManager.GetString("RuleEnd_Date_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule start date is not provided..
        /// </summary>
        public static string RuleStart_Date_Missing {
            get {
                return ResourceManager.GetString("RuleStart_Date_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get gateway error while retrieving document.
        /// </summary>
        public static string SearchPatient_GateWayResponse_Error {
            get {
                return ResourceManager.GetString("SearchPatient_GateWayResponse_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid demographics.
        /// </summary>
        public static string SearchPatient_Invalid_Demographics {
            get {
                return ResourceManager.GetString("SearchPatient_Invalid_Demographics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date of birth..
        /// </summary>
        public static string SearchPatient_Invalid_Demographics_DOB {
            get {
                return ResourceManager.GetString("SearchPatient_Invalid_Demographics_DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid last name..
        /// </summary>
        public static string SearchPatient_Invalid_Demographics_FamilyName {
            get {
                return ResourceManager.GetString("SearchPatient_Invalid_Demographics_FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid gender.
        /// </summary>
        public static string SearchPatient_Invalid_Demographics_Gender {
            get {
                return ResourceManager.GetString("SearchPatient_Invalid_Demographics_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid first name..
        /// </summary>
        public static string SearchPatient_Invalid_Demographics_GivenName {
            get {
                return ResourceManager.GetString("SearchPatient_Invalid_Demographics_GivenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPIID not provided..
        /// </summary>
        public static string SearchPatient_Missing_Demographics_MPIID {
            get {
                return ResourceManager.GetString("SearchPatient_Missing_Demographics_MPIID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple patient records found..
        /// </summary>
        public static string SearchPatient_Multiple_Record_Found {
            get {
                return ResourceManager.GetString("SearchPatient_Multiple_Record_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHINCommunity is missing..
        /// </summary>
        public static string SearchPatient_NHINCommunities_Missing {
            get {
                return ResourceManager.GetString("SearchPatient_NHINCommunities_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections missing in referral document..
        /// </summary>
        public static string Sections_Missing_In_Referral_Document {
            get {
                return ResourceManager.GetString("Sections_Missing_In_Referral_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid list of communities, to be imported..
        /// </summary>
        public static string Select_Community_to_Import {
            get {
                return ResourceManager.GetString("Select_Community_to_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select purpose as emergency.
        /// </summary>
        public static string Select_Pupose_As_Emergency {
            get {
                return ResourceManager.GetString("Select_Pupose_As_Emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a record..
        /// </summary>
        public static string Select_Record_To_Close {
            get {
                return ResourceManager.GetString("Select_Record_To_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select valid .csv file..
        /// </summary>
        public static string Select_Valid_Csv_File {
            get {
                return ResourceManager.GetString("Select_Valid_Csv_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select valid file..
        /// </summary>
        public static string Select_Valid_File {
            get {
                return ResourceManager.GetString("Select_Valid_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select valid .xls or .xlsx file..
        /// </summary>
        public static string Select_Valid_Xls_File {
            get {
                return ResourceManager.GetString("Select_Valid_Xls_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records imported successfully, except for communit(y|ies):({0}), as they already exist..
        /// </summary>
        public static string Some_Exist_Records_Not_Imported {
            get {
                return ResourceManager.GetString("Some_Exist_Records_Not_Imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State is not provided..
        /// </summary>
        public static string State_Is_Missing {
            get {
                return ResourceManager.GetString("State_Is_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User preferences has been shared to enable account access, across system(s)..
        /// </summary>
        public static string Successful_Export_Certificate_Message {
            get {
                return ResourceManager.GetString("Successful_Export_Certificate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some errors occurred while processing..
        /// </summary>
        public static string UnknownException {
            get {
                return ResourceManager.GetString("UnknownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id is not provided..
        /// </summary>
        public static string UserId_Missing {
            get {
                return ResourceManager.GetString("UserId_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code is not provided..
        /// </summary>
        public static string ZipCode_Missing {
            get {
                return ResourceManager.GetString("ZipCode_Missing", resourceCulture);
            }
        }
    }
}
